# Challenge
In this challenge we are going to focus on a very common case in software developement: merge failures.
This case arises when a contributor(not you) pushes changes to the branch, then you modify the same files 
(an old version that doesn't have your collaborator code) and try to push to the same branch.

### Your task:
- Add a power function to the calculator.py (simply take a number and multiply it by itself)
def power(x):
    return x * x
- Add and commit the calculator file.
- Try to push to challenge05
- run git pull -u origin challenge05
- fix the conflicts and push to the remote.

# Solution 
The solution is available under solution.txt

